spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flashsale?characterEncoding=utf-8&userSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCp
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.iabql.flashsale.pojo

logging:
  level:
    com.iabql.flashsale.mapper: debug

